name: work space build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && 
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && 
          . "$HOME/.cargo/env" &&
          cargo install cross --git https://github.com/cross-rs/cross
        shell: bash
        
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Build tests
        run: |
          source "$HOME/.cargo/env" &&
          cross build --target arm-unknown-linux-gnueabihf --release
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-binary
          path: target/arm-unknown-linux-gnueabihf/release/

  release:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-binary
        
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ github.ref_name }}"
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: robo2_main
          asset_name: robo2_main
          asset_content_type: application/octet-stream
